name: Daily Refuge Availability Scraper

on:
  schedule:
    - cron: '0 6 * * *' # Runs every day
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4

      - name: Run refuge availability scraper
        run: |
          python script/scrap_availabilities.py

      - name: Commit and push updated data
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add docs/refuge_availabilities.json
          git commit -m "Update refuge availabilities [CI skip]" || echo "No changes to commit"
          git push https://x-access-token:${GH_TOKEN}@github.com/maxenceprog/nuit-en-montagne

name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or master if that's your default branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist