name: Daily Refuge Availability Scraper

on:
  schedule:
    - cron: '0 6,16 * * *'
  workflow_dispatch:


jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4

      - name: Run refuge availability scraper
        run: |
          python script/scrap_availabilities.py

      - name: Update Gist with fresh data
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          gh gist edit c9fd8f1ee13451084c0c1d1a30e041ca src/data/refuge_availabilities.json
